import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from '@clerk/ui/themes';
import { Toaster } from "@/components/ui/sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider apperance={{
      theme: neobrutalism,
    }}>

      <html
        lang="en"
        suppressHydrationWarning
      >
        <body className={`${inter.className}`}>
          <Header />
          <main className="min-h-screen">
            {children}
          </main>
          <Toaster richColors/>
          <footer className="max-w-6xl mx-auto flex justify-center items-center">
            <p className="text-stone-500 text-sm">Made with ❤️ by Vansh</p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
