import { Camera, BookOpen, ChefHat, Search } from "lucide-react";

export const SITE_STATS = [
  { label: "Free Scans", val: "10/mo" },
  { label: "Recipes Generated", val: "1M+" },
  { label: "Cost to Start", val: "$0" },
  { label: "App Store Rating", val: "4.9" },
];

export const FEATURES = [
  {
    title: "Scan Your Pantry",
    description:
      "Photo recognition that actually works. Know what you have instantly.",
    icon: Camera,
    limit: "10 scans/mo free",
  },
  {
    title: "AI Chef Suggestions",
    description:
      "Turn random ingredients into a gourmet meal. Zero food waste.",
    icon: ChefHat,
    limit: "5 meals/mo free",
  },
  {
    title: "Search Any Dish",
    description:
      "Find any recipe instantly. Filter by cuisine, time, or dietary needs.",
    icon: Search,
    limit: "Unlimited searches",
  },
  {
    title: "Digital Cookbook",
    description: "Save your favorites. Export as PDF. Share with family.",
    icon: BookOpen,
    limit: "3 saves/mo free",
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: "01",
    title: "Scan",
    desc: "Point camera at fridge. AI identifies ingredients.",
  },
  {
    step: "02",
    title: "Select",
    desc: "Choose a generated recipe based on your mood.",
  },
  {
    step: "03",
    title: "Savor",
    desc: "Follow simple steps. Eat delicious food.",
  },
];

// Helper function for category emojis
export function getCategoryEmoji(category) {
  const emojiMap = {
    Beef: "🥩",
    Chicken: "🍗",
    Dessert: "🍰",
    Lamb: "🍖",
    Miscellaneous: "🍴",
    Pasta: "🍝",
    Pork: "🥓",
    Seafood: "🦐",
    Side: "🥗",
    Starter: "🥟",
    Vegan: "🥬",
    Vegetarian: "🥕",
    Breakfast: "🍳",
    Goat: "🐐",
  };
  return emojiMap[category] || "🍽️";
}

// Helper function for country flags
export function getCountryFlag(country) {
  const emojiMap = {
    American: "🗽",
    British: "👑",
    Canadian: "🍁",
    Chinese: "🐉",
    Croatian: "⚽",
    Czech: "🍺",
    Danish: "🧜",
    Dutch: "🌷",
    Egyptian: "🐫",
    Ethiopian: "☕",
    Filipino: "🌴",
    Finnish: "🦌",
    French: "🥐",
    German: "🍺",
    Greek: "🏛️",
    Hungarian: "🌶️",
    Icelandic: "🌋",
    Indian: "🪷",
    Indonesian: "🌋",
    Irish: "☘️",
    Israeli: "🕍",
    Italian: "🍕",
    Jamaican: "🌴",
    Japanese: "🗾",
    Jordanian: "🏜️",
    Kenyan: "🦒",
    Korean: "🥢",
    Lebanese: "🌲",
    Malaysian: "🌺",
    Mexican: "🌮",
    Mongolian: "🐎",
    Moroccan: "🕌",
    Nepalese: "🏔️",
    New_Zealander: "🥝",
    Nigerian: "🦅",
    Norwegian: "❄️",
    Pakistani: "🕌",
    Palestinian: "🕊️",
    Peruvian: "🦙",
    Polish: "🦅",
    Portuguese: "🚢",
    Romanian: "🧛",
    Russian: "❄️",
    Saudi_Arabian: "🕋",
    Scottish: "🎻",
    Serbian: "🏰",
    Singaporean: "🦁",
    Slovakian: "🏔️",
    Slovenian: "⛰️",
    South_African: "🦁",
    Spanish: "💃",
    Sri_Lankan: "🐘",
    Swedish: "🫎",
    Swiss: "🧀",
    Syrian: "🏛️",
    Taiwanese: "🧋",
    Thai: "🛕",
    Tunisian: "🏜️",
    Turkish: "🧿",
    Ukrainian: "🌻",
    Uruguayan: "⚽",
    Venezuelan: "🌞",
    Vietnamese: "🍜",

    Afghan: "🏔️",
    Albanian: "🦅",
    Algerian: "🏜️",
    Andorran: "⛷️",
    Angolan: "🦒",
    Argentinian: "⚽",
    Armenian: "⛰️",
    Australian: "🦘",
    Austrian: "🎼",
    Azerbaijani: "🔥",
    Bahraini: "🏝️",
    Bangladeshi: "🛶",
    Barbadian: "🏖️",
    Belarusian: "🌲",
    Belgian: "🍫",
    Belizean: "🐠",
    Beninese: "🌴",
    Bhutanese: "🐉",
    Bolivian: "🦙",
    Bosnian: "🏞️",
    Botswanan: "🐘",
    Brazilian: "🌴",
    Bruneian: "🕌",
    Bulgarian: "🌹",
    Cambodian: "🛕",
    Cameroonian: "🦁",
    Chilean: "🗻",
    Colombian: "☕",
    Costa_Rican: "🦜",
    Cuban: "🥁",
    Cypriot: "🏖️",
    Dominican: "🏝️",
    Ecuadorian: "🐢",
    Emirati: "🏙️",
    Estonian: "🌲",
    Fijian: "🌺",
    Ghanaian: "🥁",
    Guatemalan: "🦜",
    Honduran: "🌴",
    Iranian: "🕌",
    Iraqi: "🌴",
    Kazakh: "🦅",
    Kuwaiti: "🛢️",
    Kyrgyz: "🐎",
    Laotian: "🐘",
    Latvian: "🌲",
    Lithuanian: "🌾",
    Luxembourgish: "🏰",
    Malagasy: "🦎",
    Maldivian: "🏝️",
    Maltese: "⛵",
    Mauritian: "🐬",
    Mozambican: "🌊",
    Namibian: "🐘",
    Nepalese: "🏔️",
    Omani: "🕌",
    Panamanian: "🚢",
    Paraguayan: "🧉",
    Qatari: "🏙️",
    Salvadoran: "🌋",
    Senegalese: "🦁",
    Sudanese: "🐪",
    Tanzanian: "🦓",
    Ugandan: "🦍",
    Uzbek: "🏜️",
    Yemeni: "☕",
    Zambian: "🦁",
    Zimbabwean: "🦓",
  };

  return emojiMap[country] ?? "🌍";
}